### ISSUE TITLE
Picking the wrong tenant

### ISSUE THREAD

**Issue by christophwille** [Smartersoft/identity-client-assertion#8]
I am executing super-simple test code:

```
    var client = new SecretClient(new Uri(kvUri), new DefaultAzureCredential());
    var secret = await client.GetSecretAsync(secretName);
```

F5 is fine. Running with docker I get (yes, I pass the env var, I see output for az-akv-proxy)

```
Azure.RequestFailedException: AKV10032: Invalid issuer. Expected one of https://sts.windows.net/guid1/, https://sts.windows.net/guid2/, https://sts.windows.net/guid3/, found https://sts.windows.net/guid0/.
Status: 401 (Unauthorized)
ErrorCode: Unauthorized
```

guid0 is the main AAD, guid1 would the correct one for the KV resource/subscription. Even passing new DefaultAzureCredentialOptions() { TenantId = "guid1" }) to the ctor of DefaultAzureCredential fails me.

guid1 is a tenant where my guid0 account is a guest in. Is there any way to easily see in az-akv-proxy output which cred provider it actually picked and what the defaults were?

**Comment by svrooij** [comment]
You to be totally clear, you are using the `http://localhost:5616/api/msi/forward` endpoint in docker and expect it to pick the correct client?

You're right it only picks the default tenant on your local machine. This is unforeseen, I guess I need to add this query parameter to the forward endpoint.

https://github.com/Smartersoft/identity-client-assertion/blob/5dcad741208cf62e9b10599d969c0eb3da5d9094/src/Smartersoft.Identity.Client.Assertion.Proxy/Controllers/MsiController.cs#L31

I'm not behind my computer at the moment, but you can create a pr with the string? tenant = null parameter and add that to the DefaultAzureCredential. I guess it has to be FromRoute and then change the route to /msi/forward/{tenant?} meaning the tenant is optional?

**Comment by christophwille** [comment]
My "expectation" was "If the simple code works in VS with F5 interactively, it works with az-kv-proxy as well". That is then when the head-scratching started, with me also trying DefaultAzureCredentialOptions. The question which cred is it actually using came a little later as I was starting az-kv-proxy in pwsh instead of Developer Command Prompt because I am not only logged in in VS, but also via az login and a domain account on the local machine...

**Comment by christophwille** [comment]
Your comment made me look at the swagger and I switched from

`docker run --rm -it -e MSI_ENDPOINT="http://host.docker.internal:5616/api/Msi/forward" micontained:withtenant`

to

`docker run --rm -it -e MSI_ENDPOINT="http://host.docker.internal:5616/api/Msi/guid1/forward" micontained:withtenant`

That now works like a charm, even without me specifying DefaultAzureCredentialOptions any more.

**Comment by svrooij** [comment]
As I said, I was not behind my computer. Guess I already built that before 😯

Care to help me document?

**Comment by christophwille** [comment]
Given I found your tool via your blog post, maybe add a small Note section there about the "Invalid issuer. Expected one ..." error message so people will know right from the get-go what the problem most likely is.
